

services:
  mongo:
    image: mongo
    container_name: smartcart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: smartcart-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartcart

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  analysis:
    build:
      context: .
      dockerfile: analysis.Dockerfile
    container_name: smartcart-analysis
    ports:
      - "5002:5002"
    depends_on:
      - backend
  ai:
    build:
      context: .
      dockerfile: ai.Dockerfile
    container_name: smartcart-ai
    ports:
      - "5001:5001"
    environment:
      - GROQ_API_KEY=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
    depends_on:
      - backend

volumes:
  mongo_data:

