version: "3.8"

services:
  mongo:
    image: mongo
    container_name: smartcart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - smartcart-net

  backend:
    build: ./backend
    container_name: smartcart-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartcart
    env_file:
      - .env
    networks:
      - smartcart-net

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - smartcart-net

  ai:
    build:
      context: .
      dockerfile: ai.Dockerfile
    container_name: smartcart-ai
    ports:
      - "5001:5001"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - smartcart-net

  streamlit_analysis:
    build:
      context: .
      dockerfile: streamlit_analysis.Dockerfile
    container_name: smartcart_streamlit-analysis
    ports:
      - "8502:8502"
    depends_on:
      - mongo
    networks:
      - smartcart-net

volumes:
  mongo_data:

networks:
  smartcart-net:
    driver: bridge

 

  